# Generated by Django 4.2.28 on 2026-05-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
